# -*- coding: utf-8 -*-
"""eg_npimagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1flJXLsLzFGKE5QVO5QGweNvT3XxFQ4c5
"""

# -*- coding: utf-8 -*-

#------------------------------------------------------------------
# LEIA E PREENCHA O CABEÇALHO 
#------------------------------------------------------------------

'''

    Nome: Brenno Pereira Machado
    NUSP: -


    Ao preencher esse cabeçalho com o meu nome e o meu número USP,
    declaro que todas as partes originais desse exercício programa
    foram desenvolvidas e implementadas por mim e que, portanto, não 
    constituem desonestidade acadêmica ou plágio.
    
    Entendo que trabalhos sem assinatura devem receber nota zero e, ainda
    assim, poderão ser punidos por desonestidade acadêmica.
    Declaro também que sou responsável por todas as cópias desse
    programa e que não distribui ou facilitei a sua distribuição.
    
    Estou ciente que os casos de plágio e desonestidade acadêmica
    estarão sujeitos às penalidades descritas na página da disciplina
    na seção "Sobre colaboração em MAC0122".

    Reconheço que utilizei as seguintes fontes externas ao conteúdo 
    utilizado e recomendado em MAC0122, ou recebi auxílio das pessoas
    listadas abaixo.

    - LISTA de fontes externas utilizadas (links ou referências como livros)
        - 

    - LISTA das pessoas que me auxiliaram a fazer esse trabalho
        - 
'''

## ==================================================================


import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

## ------------------------------------------------------------------
def main():

    lista = list(range(20))
    ar = np.array(lista).reshape(4,5)
    img1 = NPImagem( (0, 0), ar)  # 
    print(f"img1:\n{img1}")
    print(f"Shape de img1: {img1.shape}\n")

    img2 = NPImagem( (4, 3), 100)
    print(f"img2:\n{img2}")
    print(f"Shape de img2: {img2.shape}\n")

    img2[1,2] = -10
    print(f"img2[1,2]={img2[1,2]}")
    print(f"img2:\n{img2}\n")

    img3 = img2.crop() ## cria uma cópia
    print(f"img3:\n{img3}\n")

    img4 = img1.crop(0, 1, 3, 4)  
    print(f"img4:\n{img4}\n")

    img5 = NPImagem( (3,2) )
    print(f"img5:\n{img5}\n")

    img6 = img1.crop(1,2)
    print(f"img6:\n{img6}\n")


    print("\n\n###### TESTES EG: PINTE #######\n")

    lista = list(range(30))
    ar = np.array(lista).reshape(5,6)
    img1 = NPImagem( (0, 0), ar)  # 
    print(f"img1:\n{img1}")
    print(f"Shape de img1: {img1.shape}\n")

    img2 = NPImagem( (3, 2), 100)
    img3 = img2.crop() ## cria uma cópia
    img2[2,1] = -10
    print(f"img2[1,2]={img2[2,1]}")
    print(f"img2:\n{img2}\n")
    print(f"img3:\n{img3}\n")

    img1.pinte_retangulo(1,2,3,5,99)
    print(f"img1.pinte_retangulo(1,2,3,5,99):\n{img1}\n")

    img2.pinte_retangulo(-1,-2,1,2,88)
    print(f"img2.pinte_retangulo(-1,-2,1,2,88):\n{img2}\n")

    img3.pinte_retangulo(1,0,3,4,77)
    print(f"img3.pinte_retangulo(1,0,3,4,77):\n{img3}\n")


    print("\n\n###### TESTES EG: PASTE #######\n")
    img1.paste(img2, 1, 2)
    print(f"img1.paste(img2,1,2):\n{img1}\n")

    img1.paste(img3, 3, 5)
    print(f"img1.paste(img3,3,5):\n{img1}\n")

    img1.paste(img3, -1, -1)
    print(f"img1.paste(img3,-1,-1):\n{img1}\n")


    print("\n\n###### TESTES EG: MATPLOTLIB #######\n")

    fname = 'elvis.png'
    image = mpimg.imread(fname)
    gray = np.array(image)[:,:,2] ## pega canal G da imagem RGB

    elvis = NPImagem( (), gray ) # transforma o array em uma NPImagem
    print("elvis.shape: ", elvis.shape)
    plt.gray()
    plt.imshow(elvis.data)
    plt.show()

    composicao = NPImagem( (), gray ).copia()

    fname = 'einstein.png'
    image = mpimg.imread(fname)
    gray = np.array(image)[:,:,2] ## pega canal G da imagem RGB

    einstein = NPImagem( (), gray)
    print("einstein.shape", einstein.shape)

    plt.imshow(einstein.data)
    plt.show()

    composicao.paste(einstein.crop(20,30,225,180),50,470)
    plt.imshow(composicao.data)
    plt.show()

## ------------------------------------------------------------------
class NPImagem:

    def __init__(self, shape, val=0):
        ''' (NPImagem, tuple, obj) -> None
        Constrói um objeto do tipo NPImagem com os atributos:
        self.data : variavel do tipo np.darray, valor(es) de 'val'
        self.shape: tupla que armazena as dimensões da matriz
        '''

        if type(val) is np.ndarray:
            self.data = val
        else:
            self.data = np.full(shape, val)
        
        self.shape = self.data.shape
    
    # ---------------------------------------------------------------
    def pinte_retangulo(self, sup, esq, inf, dir, v=0):
        ''' (NPImagem, int, int, int, int, int) -> None 
        Recebe 4 inteiros que definem o canto superior-esquerdo (sup, esq) e
        o canto inferior-direito (inf,dir) de uma região retangular com 
        relação a posição (0,0) de self, ou seja, os cantos são "deslocamentos" 
        em pixeis com relação à origem.
        Esse método pinta, com o valor v, os pixeis de self que tenham sobreposição com o retângulo (sup,esq)x(inf,dir). 
        '''
        self_nlins, self_ncols = self.shape
        other_nlins, other_ncols = inf - sup, dir - esq

        if (sup >= self_nlins) or (esq >= self_ncols) or (inf <= 0) or (dir <= 0): return

        
        self_sup = max(sup, 0)
        self_esq = max(esq, 0)

        self_inf = min(sup + other_nlins, self_nlins)
        self_dir = min(esq + other_ncols, self_ncols)
      
        self.data[self_sup:self_inf, self_esq:self_dir] = v

    # ---------------------------------------------------------------
    def paste(self, other, sup, esq):
        '''(NPImagem, NPImagem, int, int) -> None
        Recebe um objeto NPImagem other e par de inteiros (sup, esq) 
        que indica um deslocamento em relação à origem de self (posição (0,0)) 
        onde a NPImagem other deve ser sobreposta sobre self. Observe que
        esse deslocamento pode ser negativo. 
        '''

        linha_final = other.shape[0] + sup 
        coluna_final = other.shape[1] + esq

        l,c = None, None
        l_final,c_final = None, None

        #Caso a matriz a ser colada seja maior que a que recebe 
        if linha_final > self.shape[0]:
            l_final = self.shape[0] - sup
            linha_final = self.shape[0]
        if coluna_final > self.shape[1]:
            c_final = self.shape[1] - esq
            coluna_final = self.shape[1]

        # Caso a matriz seja colada antes do início da que recebe
        if sup < 0 :
            l = abs(sup)
            sup = 0
        if esq < 0 :
            c = abs(esq)
            esq = 0

        self.data[sup:linha_final, esq:coluna_final] = other.data[l:l_final,c:c_final]

    # ---------------------------------------------------------------
    def __getitem__(self, key):
        ''' (NPImagem, tupla) -> self.data.dtype
        Recebe uma tupla key contendo a posição (lin, col)
        e retorna o item nessa posição em NPImagem.data[lin,col].
        '''

        return self.data[key]

    # ---------------------------------------------------------------
    def __setitem__(self, key, valor):
        ''' (NPImagem, tupla, obj) -> None
        Recebe uma tupla key contendo a posição (lin, col)
        e um objeto valor e armazena o valor na posição self.data[lin,col].
        '''

        self.data[key] = valor

    # ---------------------------------------------------------------
    def __str__(self):
        ''' (NPImagem) -> str
        Ao ser usada pela função 'print', deve exibir o mesma saída que
        a um objeto do tipo np.darray

        Exemplo: para self.data = np.full((2,3), 0)
        o método deve retornar a string 
        "[[ 0  0  0]
          [ 0  0  0]]" 
        '''

        return f"{self.data}"
        
    # ---------------------------------------------------------------
    def crop(self, sup=None, esq=None, inf=None, dir=None):
        '''(NPImagem, int, int, int int) -> NPImagem
        Recebe uma referência 'self' do tipo NPImagem e quatro numeros 
        inteiros (sup, esq, inf, dir). Retorna uma variavel 'copia' do
        tipo NPimagem que tem dimensões e valores iguais a fatia do 
        tipo np.array self.data[sup:inf,esq:dir]
        '''
        if not (sup or esq or inf or dir):
            copia = self.copia()
        else:
            copia = NPImagem((0,0),self.data[sup:inf,esq:dir].copy())
        
        return copia
    
    # ---------------------------------------------------------------
    def copia(self):
        '''(NPImagem) -> NPImagem
        Recebe uma referência 'self' do tipo NPImagem.
        Retorna uma cópia de 'self'
        '''

        copia_np = NPImagem((0,0), self.data.copy())
        
        return copia_np

## ==================================================================
if __name__ == '__main__':
    main()

