# -*- coding: utf-8 -*-
"""eg_array2d.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NwsqjEsLDWP0Sn3Lw-PdQChDTUL_toYS
"""

# -*- coding: utf-8 -*-

#------------------------------------------------------------------
# LEIA E PREENCHA O CABEÇALHO 
#------------------------------------------------------------------

'''
    GRUPO: 5

    Nome: Brenno Pereira Machado
    NUSP: 6434401

    Nome: Bruno Kinsch de Lara Campos
    NUSP: 12557376

    Nome: Carlo Chede Broggi
    NUSP: 10694000


    Ao preencher esse cabeçalho com o meu nome e o meu número USP,
    declaro que todas as partes originais desse exercício programa
    foram desenvolvidas e implementadas por mim e que, portanto, não 
    constituem desonestidade acadêmica ou plágio.
    
    Entendo que trabalhos sem assinatura devem receber nota zero e, ainda
    assim, poderão ser punidos por desonestidade acadêmica.
    Declaro também que sou responsável por todas as cópias desse
    programa e que não distribui ou facilitei a sua distribuição.
    
    Estou ciente que os casos de plágio e desonestidade acadêmica
    estarão sujeitos às penalidades descritas na página da disciplina
    na seção "Sobre colaboração em MAC0122".

    Reconheço que utilizei as seguintes fontes externas ao conteúdo 
    utilizado e recomendado em MAC0122, ou recebi auxílio das pessoas
    listadas abaixo.

    - LISTA de fontes externas utilizadas (links ou referências como livros)
        - 

    - LISTA das pessoas que me auxiliaram a fazer esse trabalho
        - 
'''

## ==================================================================

def main():

    print("Testes da classe Array2d\n")

    a = Array2d( (2,3), 3) # cria Array2d com valor inicial 3
    print(f'Criação do Array2d a:')
    print(a)
    print(f'shape: {a.shape}')
    print(f'size : {a.size}')
    print(f'data : {a.data}')
    print()

    a.resize( (3,2) )
    print(f'novo a depois de resize:')
    print(a)
    print(f'shape: {a.shape}')
    print(f'size : {a.size}')
    print(f'data : {a.data}')

    print("\n\n####__SUB__ e __RSUB__ ###\n\n")

    a = Array2d( (2,3), 3) # cria Array2d com valor inicial 3
    print(f'teste 1: Criação do Array2d a:')
    print(a)
    print(f'shape: {a.shape}')
    print(f'size : {a.size}')
    print(f'data : {a.data}')
    print()

    b = Array2d( (2,3), 7)   # criar Array2d com valor inicial 7
    print(f'teste 2: Criação do Array2d b:')
    print(b)
    print(f'shape: {b.shape}')
    print(f'size : {b.size}')
    print(f'data : {b.data}')
    print()

    # sub e rsub
    x = a - b
    print(f'teste: x = a - b ')
    print(x)  
    print()

    y = a - 2
    print(f'teste: y = a - 2 ')
    print(y) 
    print()

    z = 3.14 - b
    print(f'teste: z = 3.14 - b ')
    print(z) 
    print()

    print("\n\n#####__MUL__ e __RMUL__######\n\n")

    # mul e rmul
    c = a * x
    print(f'teste: c = a * x ')
    print( c )  
    print()

    d = c * -1
    print(f'teste: d = c * -1 ')
    print( d ) 
    print()

    e = 0.5 * b
    print(f'teste: e = 0.5 * b ')
    print( e ) 
    print()

    a = Array2d( (2,3), 3) # cria Array2d com valor inicial 3
    print(f'teste 1: Criação do Array2d a:')
    print(a)
    print(f'shape: {a.shape}')
    print(f'size : {a.size}')
    print(f'data : {a.data}')
    print()

    b = Array2d( (2,3), 1.7)   # criar Array2d com valor inicial 7
    print(f'teste 2: Criação do Array2d b:')
    print(b)
    print(f'shape: {b.shape}')
    print(f'size : {b.size}')
    print(f'data : {b.data}')
    print()

    print(f'teste 3: a[0,1] + 100 é: {a[0,1] + 100}') # acesso direto usando tupla: use o método __getitem__
    print()

    a[1,1] = -1    # atribuição usando tupla: use o método __setitem__
    print(f'teste 4: Array2d a:')
    print(a)

## ==================================================================
#   A classe Array2d permite a manipulação de 'matrizes' de duas 
#   dimensões. O exercício é utilizar uma lista linear, ao invés
#   de uma lista aninhada, para armazenar os dados da matriz 
#   internamente.
#   A lista linear deve ser um atributo de nome 'data'.

class Array2d:

    # ---------------------------------------------------------------
    def __init__(self, shape, val):
        ''' (Array2d, tuple, obj) -> None
        Constrói um objeto do tipo Array2d com os atributos:
        data : lista onde os valores são armazenados
        shape: tupla que armazena as dimensões da matriz
        size : número total de elementos da matriz
        '''
         
        self.shape = shape
        self.size = shape[0]*shape[1]
        self.data = self.size*[val]

    def resize (self, novo_shape):
      ''' (Array2d, tuple) -> None
      '''

      self.shape = novo_shape

    # ---------------------------------------------------------------

    def __sub__(self, b):
      '''
      (Array2d, Array2d) -> Array2d
      '''

      
      if type(b) == int or type(b) == float:
        b = Array2d(self.shape, b)

      if self.shape[0] == b.shape[0] and self.shape[1] == b.shape[1]:
        a = []
        for i in range(b.size):
          a += [ self.data[i] - b.data[i] ]
      else:
        return "erro"
      
      resultado = Array2d(b.shape, 0)
      resultado.data = a[:]

      return resultado

    # ---------------------------------------------------------------

    def __rsub__(self, b):
      '''(Array2d, Array2d) -> Array2d
      '''

      if type(b) == int or type(b) == float: 
        b = Array2d(self.shape, b)

      return b - self

    # ---------------------------------------------------------------

    def __mul__(self, b):
      ''' (Array2d, Array2d) -> Array2d
      '''

      if type(b) == int or type(b) == float:
        novo_data = []
        for elemento in self.data:
          novo_data.append(elemento * b)
        resultado = Array2d(self.shape, 0)
        resultado.data = novo_data[:]
        return resultado
      
      novo_data = []

      for i in range(self.size):
        novo_data.append(self.data[i]*b.data[i])
      
      resultado = Array2d(self.shape, 0)
      resultado.data = novo_data[:]
      return resultado

    def __rmul__(self, b):
      ''' (Array2d, Array2d) -> Array2d
      '''
      
      return self * b

    # ---------------------------------------------------------------
    def __getitem__(self, key):
        ''' (Array2d, tupla) -> obj
        recebe uma tupla key contendo a posição (lin, col)
        e retorna o item nessa posição do Array2d self.

        Esse método é usado quando o objeto é chamado com 
        uma tupla entre colchetes, como self[0,0]. 
        Exemplo:
        >>> a = Array2d( (2,3), -1)
        >>> a[1,1] + 100
        99
        >>> print( a[1,1] )
        -1
        '''

        lin, col = key
        return self.data[ self.shape[1]*lin + col]

    # ---------------------------------------------------------------
    def __setitem__(self, key, valor):
        ''' (Array2d, tupla, obj) -> None
        recebe uma tupla key contendo a posição (lin, col)
        e um objeto valor e armazena o valor nessa posição
        do Array2d self.

        Esse método é usado para atribuir 'valor' na posição
        indicada pela tupla `key`, como self[0,0] = 0. 
        Exemplo:
        >>> a = Array2d( (2,3), -1)
        >>> print( a[1,1] )
        -1
        >>> a[1,1] = 100
        >>> print( a[1,1] )
        100
        '''

        lin, col = key
        self.data[ self.shape[1]*lin + col] = valor

    # ---------------------------------------------------------------
    def __str__(self):
        ''' (Array2d) -> str
        ao ser usada pela função print, deve exibir cada linha
        do Array2d em uma linha separada, separando seus elementos por um espaço.

        Exemplo: para self.data = [1, 2, 3, 4, 5, 6] e self.shape = (2,3)
        o método deve retornar a string 
        "1 2 3\n4 5 6" 
        e, caso self.shape = (3,2) o método deve retornar a string
        "1 2\n3 4\n5 6" 
        '''
        i = 0
        array = ""
        for elemento in self.data:
            i += 1
            array += str(elemento) + " "
            if i == self.shape[1]:
                array = array[:-1] + "\n"
                i = 0

        return array[:-1]

    # ---------------------------------------------------------------
    # Escreva outros métodos e funções caso desejar


## ==================================================================

if __name__ == '__main__':
    main()

